Calc command
mwillsey/egg-smol pull request #76
Opened 2022-12-08 22:05 UTC by philzook58

[Dafny](http://dafny.org/dafny/DafnyRef/DafnyRef.html#sec-calc-statement) and [Lean](https://github.com/leanprover-community/leanprover-community.github.io/blob/newsite/templates/extras/calc.md) both have a notion of a calculational proof. Agda also has a style like this.
This is a proof command that allows one to break up a proof with user given hints.
```
(calc ((a G) (b G))
    (* (* b (* (inv a) a)) (inv b))
    (* b (inv b))
    (I)
)
```
It works by 
1. pushing the egraph
2. inserting fresh constants (eids) as `a` and `b`. This is a way of asking a universally quantified question.
3. inserting pairs of subsequent entries of the calc command.
4. running until the two are found to be equal.
5. popping all of this out of the egraph

 It could also work in a unidirectional mode by only inserting the first of the pair and seeking the second. This would also support calc in the `->` implication mode (inserting a fact and seeing when the consequent is derived).

This could possibly be a macro.

The way the universal quantification works here is a little goofy. I believe it is sound, but the way shadowing and scoping works is not typical. You may not make a previously defined name. For example, this will error out. Possibly in the future there needs to be a reserved internal namespace, or the ability to locally shadow tables.
```
(calc ((I G) (b G))
    (* (* b (* (inv a) a)) (inv b))
    (* b (inv b))
    (I)
)
```

A possible option that might be nice is an `:assert` flag that asserts the calc lemma as an axiom after it is proven.

Another proof command I'm excited for is a related lambda prolog-lite top down prover.

2022-12-08 23:32 UTC, mwillsey requested changes

2022-12-08 23:32 UTC, mwillsey commented on tests/calc.egg
> +; With rules filling it in with different stop conditions of interest.
Vestigal comments from a previous PR perhaps?

2022-12-08 23:32 UTC, mwillsey commented on src/lib.rs
> +                self.pop()?;
unwrap this pop, it shouldn't fail.

2022-12-08 23:32 UTC, mwillsey commented on src/lib.rs
> +            self.pop()?;
unwrap this

2022-12-08 23:32 UTC, mwillsey commented on src/lib.rs
> +        if let Some(a) = iter.next() {
Something goofy is happening with this loop structure. Could you refactor into a loop over [`exprs.windows (2)`](https://doc.rust-lang.org/stable/std/primitive.slice.html#method.windows)? Also no need to `if let` this whole thing, I think just bailing early if `exprs.len() < 2` would suffice.

2022-12-08 23:32 UTC, mwillsey commented on src/lib.rs
> +                self.pop()?;
unwrap this, it shouldn't fail.

2022-12-09 00:05 UTC, philzook58 commented
Another musing:
The calc command is rather close to being a `sketch` command if it was unidirectional and allowed existentials. https://arxiv.org/pdf/2111.13040.pdf

2022-12-09 17:37 UTC, mwillsey approved these changes

2022-12-09 17:38 UTC, merged